### ISSUE TITLE
v5 component refactor: App Bar

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/elements#153] opened 2024-08-15 05:55 UTC
**Abstract**

_As part of the v5 Elements release, each component will be reviewed and refactored to ensure best practice and design system alignment_

**Specification**

- Is new component or existing? Existing 'Nav' 
- Is the component being re-named? Rename to 'App Bar' 
- Is the component design signed off by product and design? Yes 
- [Guide to component structure & documentation in storybook](https://github.com/reapit/elements/wiki/Developer-Contribution-Guide)
- [Link to DS in Figma](https://www.figma.com/design/6CaivqdlTX0UkFYJkpBKDu/Reapit-DS?node-id=428-7209&t=wNqPmfN0KOgru0jN-4)
- [Link to Elements Audit in Figma](https://www.figma.com/design/XJ6qcAV8gHscsUodqJMNEF/App-bar-and-Side-nav-%5BElements%5D?node-id=18-7578&t=AB2erFDHYuLLxvGj-4)
- [Accessibility requirements](https://m3.material.io/components/top-app-bar/accessibility)
- [Link to Design Guidelines](https://www.figma.com/design/pJ96bxoEFStjjIbAPy0Jaj/Design-Guidelines?node-id=945-25707&t=mvIlOCZjDYP90TZT-4)

**Developer Checklist**

- [ ] Styles alignment between Design System and Elements
- [ ] Check design tokens in Figma and implement CSS variable tokens if available for relevant component
- [ ] Align with accessibility standards / spec as per above
- [ ] If relevant, break down component into `Styles Only` and `React` component structures
- [ ] Ensure all variants of components are documented as appropriate 
- [ ] Ensure unit test coverage is adequate for component
- [ ] Update documentation in MDX file as per guidelines
- [ ] Changelog updated to reflect a single beta version per component ideally

**Release Checklist**

- [ ] Approved PR merged to main
- [ ] Design & product review and feedback addressed by developer
- [ ] Beta release by product / engineering lead to next beta version

**Additional Context or Information**

**Comment by jmatiushina** [comment] 2024-08-21 07:28
Pointing out the issue I've had as if it might be relevant to the task and helpful for who ever picks it up. I'm passing in `brandOptions`:
```
brandOptions={{
            callback: openNewPage('agencycloud://process/webpage?url=https://mysite.com'),
            logoUrl: 'https://uk.payprop.com/res/assets/img/pp_logo.svg',
          }}
```
As you can see I'm trying to redirect to the webpage outside of the agency cloud.
Open new page uses `window.open` which I thought would solve my issue.
```
export const openNewPage = (uri: string) => () => {
  window.open(uri, '_blank')
}
```
In the use-case described above my logo is not clickable within the agency cloud and redirect isn't happening.
I have checked the link itself and the issue disappears if I use an href.
```
<a href="agencycloud://process/webpage?url=https://mysite.com">My site</a>
```
Within current component there is no `href` option. Maybe we can add it with v5 refactor?
cc @HollyJoyPhillips

**Comment by kurtdoherty** [comment] 2024-08-28 21:45
**suggestion:** @adrian-reapit Like a few of the other v5 tickets currently on the board that I've commented on, I think this is another one that needs to move away from a config-first component API to a composition-first one. What I mean by this is, instead of trying to facilitate all possible configurations of the app bar and the various pieces involved in it within a single prop interface, we really need to lean into composing separate components together via JSX, as that's "the React way".

By composition, I mean something like:

```javascript
<GlobalAppBar
  brand={<MyBrandLogo />}
  nav={<MyTopNav />}
  utilities={<MyUtilityIcons />}
/>
```

Here, the `GlobalAppBar` component is really just handling the layout of the other "slots". Consumers would then _compose_ other Design System components into the appropriate slots, but they have the flexibility to configure them as necessary without `GlobalAppBar` having to explicitly support all those other component's props as well.

**aside:** I've provide a bunch of general direction (maybe opinion, depending on your perspective) on this sort of thing in [the Elements wiki](https://github.com/reapit/elements/wiki/Component-Design#general-principles). Would be great if we could have some discussion on that content in an upcoming DS working group session.

**Comment by adrian-reapit** [comment] 2024-09-02 17:13
I'm not sure AppBar is a good name for this component. A user would assume its the top bar but it contains full site navigation, some of which is outside the 'bar'. We could call it ElementsNavigation. 

The logo and search items should be fully customisable and positioned in placeholders but i think we should keep a consistent experience for the main navigation behaviour or it goes too far from the point of providing this library. The Logo component could allow full control of how the link works. @jmatiushina 

`<ElementsNavigation renderLogo={<MyLogo />}" renderSearch={<MySearchComponent />} mainNavigation={[]} secondaryNavigation={[]} appLinks={[]}>`

We are looking to allow integration of React Router Link components, or similar from other router libraries, into the main navigation so you would have the same object style control of the href as in React Router. We are working on this but it should need a top level provider which would define the link component to be used as base for a button which would appear with the Elements button styling

**Comment by kurtdoherty** [comment] 2024-09-02 23:07
> The logo and search items should be fully customisable and positioned in placeholders but i think we should keep a consistent experience for the main navigation behaviour or it goes too far from the point of providing this library.

I think we'll need to have a verbal conversation on this. I do not believe a config-style API is appropriate here; it should not be the responsibility of an app bar component to determine the how navigation items are rendered, nor the interface those navigation items have.

> We are looking to allow integration of React Router Link components, or similar from other router libraries, into the main navigation so you would have the same object style control of the href as in React Router. We are working on this but it should need a top level provider which would define the link component to be used as base for a button which would appear with the Elements button styling.

For solutions like this, I think we need to go through an RFC or solution design process in order to provide opportunity for input from consumers of Elements. In my opinion, this kind of thing isn't something Elements should be directly concerned about; it should be sufficient to provide atomic Link and Button components that consumers can easily integrate with their routing library of choice.

**Comment by nurm717123** [comment] 2024-11-18 10:59
Hi @adrian-reapit  and @kurtdoherty , now that the required component for app-bar (top-section) already available I think I can start compose them together

### Context: 
- the term app-bar here refer to the top section of the whole app-bar (as there is other section e.g side-bar, bottom-bar, mobile nav)
- the new app switcher still marked as "not ready for dev" for now
- there is 2 approach to handle mobile responsive UI, which is:
  - use defined css constants (under `src/styles/media.ts`
  - use `useMediaQuery` hook

in this case I prefer the first approach, because its faster (since its from native css) and easier for html user to use.

### Question
1. for the app switcher, should I use existing app switcher menu or temporary disable/hide it will enough ?
2. can I use https://www.w3.org/WAI/ARIA/apg/patterns/menubar (https://www.w3.org/WAI/ARIA/apg/patterns/menubar/examples/menubar-navigation/) as the a11y reference?, if I can since the example using `ul` and `li` pattern, I think I will use `ButtonGroup` with role `list` and `listitem` for the `NavItem`.
3. since there will be a lot of code to use app-bar, should we provide `ReactShorthand` for this and for the whole app-bar(later), the usage would be .eg `<AppBar navItems={[.... some nav items]} avatar={{label: "AD", items: [{... some items}]}} />` something like that
4. when the whole app bar will be called `AppBar` should this component in this ticket called `TopBar`?

### Proposal
given the context above I propose that the scope of this ticket will be the creation of the top section of the app-bar, which going to be broken down in several pr:

1. Compose the component (see if it need some split here)
2. keyboard interaction

non requirements
- animation on hamburger menu click

### code snippets
```javascript
// app-bar react consumer v1
<AppBar>
  <MainNav>
    <NavItem />
    <NavItem />
    <NavItem />
  </MainNav>
  <SecondaryNav> // this could also be called `RightSection`, and `MainNav` is `LeftSection`
    <SearchButton />
    <NavIconItem />
    <NavIconItem />
    <NavIconItem />
    <AvatarButton />
  </SecondaryNav>
</AppBar>
```
or

```javascript
// app-bar react consumer v2
<AppBar 
  mainNavItems={items as NavItemProps[]}
  avatarOptions={{
     label: "AD",
     onClick: trackAvatarClick // in addition to open menu behind the scene
     items: MenuItemProps[]
  }} 
 searchButton={{
  onClick: onClickHandler
 }}
 secondaryNav={items as NavIconItemsProps[]}
/>
```

if there is any other approach you would like to give, I would appreciate it, thanks


any other better approach please welcom

**Comment by adrian-reapit** [comment] 2024-11-18 17:32
A left/centre/right container structure would be good. Mixpanel has the same layout and uses this.

<img width="543" alt="image" src="https://github.com/user-attachments/assets/a0430efc-b712-4bd7-96fd-123fd95c7812">
<img width="1107" alt="image" src="https://github.com/user-attachments/assets/d8582f61-cba4-4d20-8173-f20cc795829c">

**Comment by nurm717123** [comment] 2024-11-19 06:05
> A left/centre/right container structure would be good. Mixpanel has the same layout and uses this.
> 
> <img alt="image" width="543" src="https://private-user-images.githubusercontent.com/152165863/387324525-a0430efc-b712-4bd7-96fd-123fd95c7812.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5OTY0MzYsIm5iZiI6MTczMTk5NjEzNiwicGF0aCI6Ii8xNTIxNjU4NjMvMzg3MzI0NTI1LWEwNDMwZWZjLWI3MTItNGJkNy05NmZkLTEyM2ZkOTVjNzgxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQwNjAyMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmFiMDgzZjhiODZiNzQyODEwODg5ZTZmZjFjY2YyYWZiN2ExZDE0ZDFkNDQ3YWZmYzIwYjNlOGYyNWVlZDQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._fe63ikKfpK-wMHDZrf8MNiHv85IhvxulHgYOoaUQCs"> <img alt="image" width="1107" src="https://private-user-images.githubusercontent.com/152165863/387324666-d8582f61-cba4-4d20-8173-f20cc795829c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5OTY0MzYsIm5iZiI6MTczMTk5NjEzNiwicGF0aCI6Ii8xNTIxNjU4NjMvMzg3MzI0NjY2LWQ4NTgyZjYxLWNiYTQtNGQyMC04MTczLWYyMGNjNzk1ODI5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQwNjAyMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjhlZmU2NjQ1MDk1Y2Q5YzhkNjBjNGE5MTM0NDVhNTAxZDZhZWE4NTcwMmExYzY0MmE3NTI4ZWIwMzY0NzQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QhGvaQ3WMZgggKz1bE4sQfuygFbWGkTAKajIwEbOA-s">

yes, I think can make it like e.g `LeftNavSection` and `RightNavSection`

**Comment by kurtdoherty** [comment] 2024-11-19 06:19
**suggestion:** I think we should avoid the use of children here, mostly because that allows the order of each section to be changed (i.e. a consumer could render the secondary nav before the primary nav). Since order is important, I think specific props are preferred over children here.

**thought:** I also wonder if it's worth breaking out the left and right content into more specific props like `appSwitcher`, `mainNavigation` and so on 🤔

**Comment by nurm717123** [comment] 2024-11-20 02:47
Thank you, @adrian-reapit and @kurtdoherty I completely agree with your points. 👍

and based on the latest discussion (some of them are in meeting), here is the update:

### Answers
> for the app switcher, should I use existing app switcher menu or temporary disable/hide it will enough ?

use the existing nav's app switcher

> since there will be a lot of code to use app-bar, should we provide ReactShorthand for this and for the whole app-bar(later), the usage would be .eg <AppBar navItems={[.... some nav items]} avatar={{label: "AD", items: [{... some items}]}} /> something like that

yes, we going to provide ReactShorthand, so the structure is standardized

> when the whole app bar will be called AppBar should this component in this ticket called TopBar?

yes, we can call it Top Bar, refer to the question I've raised [here](https://www.figma.com/design/pJ96bxoEFStjjIbAPy0Jaj?node-id=945-25708&m=dev#1031925084)

### Questions (new/old)

> yes, we can call it Top Bar, refer to the question I've raised [here](https://www.figma.com/design/pJ96bxoEFStjjIbAPy0Jaj?node-id=945-25708&m=dev#1031925084)

1. refer to above answer, what should we call the wrapper of the whole navigation bar (Top Bar, Bottom Bar, Side Bar, Mobile Nav, .etc), <AppBar />, <Nav />, <ElementsNav /> ?

2. can I use https://www.w3.org/WAI/ARIA/apg/patterns/menubar (https://www.w3.org/WAI/ARIA/apg/patterns/menubar/examples/menubar-navigation/) as the a11y reference?, if I can since the example using ul and li pattern, I think I will use ButtonGroup with role list and listitem for the NavItem.

**Comment by kurtdoherty** [comment] 2024-11-20 04:04
Hmm, I seem to have failed to read one of your early comments @nurm717123 , so I apologise for not having responded specifically to more of your original questions.

> > since there will be a lot of code to use app-bar, should we provide ReactShorthand for this and for the whole app-bar(later), the usage would be .eg <AppBar navItems={[.... some nav items]} avatar={{label: "AD", items: [{... some items}]}} /> something like that
>
> yes, we going to provide ReactShorthand, so the structure is standardized

**issue:** Can you help me understand why we planning to implement this kind of interface? It seems to me that this kind of interface breaks every SOLID design principle in the acronym while buying us very little benefit.

> > for the app switcher, should I use existing app switcher menu or temporary disable/hide it will enough ?
> 
> use the existing nav's app switcher

**question:** I'm not sure I understand the original question. What does the existing nav's app switcher have to do with this new AppBar work?

> > when the whole app bar will be called AppBar should this component in this ticket called TopBar?
> 
> yes, we can call it Top Bar, refer to the question I've raised [here](https://www.figma.com/design/pJ96bxoEFStjjIbAPy0Jaj?node-id=945-25708&m=dev#1031925084)

**praise:** Great work talking to design about the naming. TopBar makes sense in the context of side and bottom bars 👍 

**question:** I don't understand what you are referring to in your Figma comment and the comment above regarding some kind of all-in-one `<ElementsNav ... />` component. Can you help me understand what this is meant to be and what benefit it is meant to provide us?

> can I use https://www.w3.org/WAI/ARIA/apg/patterns/menubar (https://www.w3.org/WAI/ARIA/apg/patterns/menubar/examples/menubar-navigation/) as the a11y reference?

**question:** Do we need this kind of behaviour for the TopBar? What's wrong with just allowing users to tab through the nav items?

**Comment by kurtdoherty** [comment] 2024-11-20 04:17
Regarding the handling of viewport sizes:

> there is 2 approach to handle mobile responsive UI, which is:
> - use defined css constants (under src/styles/media.ts)
> - use useMediaQuery hook

While I agree that a CSS-first approach would be preferred, I think this needs some further thinking because while some of the behaviour outlined by Design is definitely related to viewport size, some of it is not. For example, the hiding of the profile menu is certainly viewport related, but the collapsing of individual main nav items is related to their container size and the size of the other main nav items, not the viewport.

In order to enable products engineering teams to handle the uniqueness of their product's main nav items, it may be prudent for us to explore whether CSS media queries are going to be sufficient in all cases, or if we need to enable the use of container queries or some other mechanism for them to express the required behaviour easily.

**Comment by nurm717123** [comment] 2024-11-20 05:51
> issue: Can you help me understand why we are planning to implement this kind of interface? It seems to me that this kind of interface breaks every design principle in the SOLID acronym, while buying us very little benefit 😰 I'm keen to understand what you see here that perhaps I don't. 
question: I don't understand what you are referring to in your Figma comment and the comment above regarding some kind of all-in-one <ElementsNav ... /> component. Can you help me understand what this is meant to be and what benefit it is meant to provide us?

so the context is, we will have multiple nav components (Top bar or Side Bar, Bottom bar, Mobile Nav, .etc) all of them have shared navigation items in common, so instead of letting the user compose it their own (which can accidentaly lead to wrong structure and wrong behavior), I think that it would be better to provide React short hand (html user can still use the class separately) e.g

```javascript
<ElementsNav leftSection={{
  appSwitcherProps,
  mainNavigations: {[
    {
       label: "nav 1"
       onClick: handleClick,
       // or
       href: '/page1'
      }
    ]
  }}
  
 rightSection={{
  avatarProps,
  searchButtonProps,
  secondaryNavigationProps: {[
    {
       label: "settings"
       onClick: handleSettingClick,
       // or
       href: '/settings'
      }
    ]
  }}
/>
```

> question: I'm not sure I understand the original question. What does the existing nav's app switcher have to do with this new TopBar work?

since the new App Switcher still marked as not ready, so I think that we still have the consumer who needed that (I've discussed it with Adrian, but I also would like to hear your opinion)

> question: Do we need this kind of behaviour for the TopBar? What's wrong with just allowing users to tab through the nav items?

my idea is the Top Bar will be part of the whole Nav component

**Comment by nurm717123** [comment] 2024-11-20 05:52
> While I agree that a CSS-first approach would be preferred, I think this needs some further thinking because while some of the behaviour outlined by Design is definitely related to viewport size, some of it is not. For example, the hiding of the profile menu is certainly viewport related, but the collapsing of individual main nav items is related to their container size and the size of the other main nav items, not the viewport.
> 
> In order to enable products engineering teams to handle the uniqueness of their product's main nav items, it may be prudent for us to explore whether CSS media queries are going to be sufficient in all cases, or if we need to enable the use of container queries or some other mechanism for them to express the required behaviour easily.

yes, I would like to experiment for that

**Comment by kurtdoherty** [comment] 2024-11-20 06:14
> > **question:** I don't understand what you are referring to in your Figma comment and the comment above regarding some kind of all-in-one <ElementsNav ... /> component. Can you help me understand what this is meant to be and what benefit it is meant to provide us?
> 
> so the context is, we will have multiple nav components (Top bar or Side Bar, Bottom bar, Mobile Nav, .etc) all of them have shared navigation items in common, so instead of letting the user compose it their own (which can accidentaly lead to wrong structure and wrong behavior), I think that it would be better to provide React short hand (html user can still use the class separately)

Thanks 🙏 
I have a lot to say on this 😅 ... but I think it would be best to descope it from this ticket and discuss it separately. Seems like that was what you were intending as well?

> > > for the app switcher, should I use existing app switcher menu or temporary disable/hide it will enough ?
> >
> > **question:** I'm not sure I understand the original question. What does the existing nav's app switcher have to do with this new TopBar work?
>
> since the new App Switcher still marked as not ready, so I think that we still have the consumer who needed that (I've discussed it with Adrian, but I also would like to hear your opinion)

I agree that, since the new App Switcher design is not ready for dev, we need to allow consumers to use the existing one, but I don't understand what that has to do with this TopBar. They are completely separate components, right? Do you just mean you'll use the existing App Switcher in the Storybook docs?

> > **question:** Do we need this kind of behaviour for the TopBar? What's wrong with just allowing users to tab through the nav items?
>
> my idea is the Top Bar will be part of the whole Nav component

Whether we have a high-level component that takes care of the top bar, side bar, mobile nav and bottom bar, my question still stands. Do we really need the `TopBar` to have the behaviour described by the WAI-ARIA menubar pattern or could we just allow users to tab through the different interactive elements that will be present in the TopBar?

**Comment by kurtdoherty** [comment] 2024-11-20 06:15
PS. If this thread grows much larger, we may need to schedule in a video call 😅

**Comment by nurm717123** [comment] 2024-11-20 06:39
> I have a lot to say on this 😅 ... but I think it would be best to descope it from this ticket and discuss it separately. Seems like that was what you were intending as well?

yes, as I mention in the context of my previous comment (forgot to copy it to my latest comment 🤦 )
> Context:
- the term app-bar here refer to the top section of the whole app-bar (as there is other section e.g side-bar, bottom-bar, mobile nav)

> I agree that, since the new App Switcher design is not ready for dev, we need to allow consumers to use the existing one, but I don't understand what that has to do with this TopBar. They are completely separate components, right?

I think app switcher is part of the TopBar in this ticket 🤔

I think we have different central reference point here, where you probably refer to [Link to DS](https://www.figma.com/design/6CaivqdlTX0UkFYJkpBKDu/Reapit-DS?node-id=428-7209&t=wNqPmfN0KOgru0jN-4) (which I think the old one) and I refering to https://www.figma.com/design/XJ6qcAV8gHscsUodqJMNEF/Reapit-Elements-production-ready-components?node-id=16-4841&m=dev

> Do you just mean you'll use the existing App Switcher in the Storybook docs?

yes

> Whether we have a high-level component that takes care of the top bar, side bar, mobile nav and bottom bar, my question still stands. Do we really need the TopBar to have the behaviour described by the WAI-ARIA menubar pattern or could we just allow users to tab through the different interactive elements that will be present in the TopBar?

yeah, my reason to asking that if because https://m3.material.io/components/top-app-bar/overview more like for mobile only view, where the WAI-ARIA is covering the desktop screen, so which one do we prefer 🤔 ?

**Comment by kurtdoherty** [comment] 2024-11-20 06:57
Re app switcher, I think this is best treated as it's own molecule that is independent of the TopBar atom, just like we have separate atoms and molecules for the main nav items, secondary nav items, avatar button and its menu etc. We will compose the two together rather than have the TopBar internally implement the AppSwitcher.

To put it another way, if we think about the Single Responsibility Principle, the `TopBar` is responsible for the correct layout of the other atoms and molecules, it is not responsible for their implementation.

On the a11y side of things, I don't have strong opinions here. Just asking if we really _need_ to invest in the menubar pattern's a11y now.

**Comment by nurm717123** [comment] 2024-11-20 07:47
Ok, I got you, so we'll put them in separate component just like (avatar-button, search-button .etc), in this case I think I'll need 4 for this:

1. Reapit Brand / Logo
2. App Switcher (defer this just in case new app switcher ready at that time 🤔)
3. Compose the Top Bar (all screen dimension)
4. keyboard interaction (a11y)

let me know if I need more 👍

**Comment by kurtdoherty** [comment] 2024-11-20 08:39
👍 

Yep, I think the logo should be separate for now too as I believe each product will have it's own unique one. I think it's too early to decide whether the product logos should be implemented in Elements or not; we may prefer for them to be in a CDN instead... e.g. Console Cloud's logo is in a CDN so we'll just want a prop for us to pass in our own component for the logo.

Re the PR breakdown, I think (1) and (2) can be done in their own tickets. This ticket is just the AppBar atom (which we're now calling TopBar), so PRs (3) and (4) should be sufficient 👍

**Comment by nurm717123** [comment] 2024-11-20 10:20
> Regarding the handling of viewport sizes:
> 
> > there is 2 approach to handle mobile responsive UI, which is:
> > 
> > * use defined css constants (under src/styles/media.ts)
> > * use useMediaQuery hook
> 
> While I agree that a CSS-first approach would be preferred, I think this needs some further thinking because while some of the behaviour outlined by Design is definitely related to viewport size, some of it is not. For example, the hiding of the profile menu is certainly viewport related, but the collapsing of individual main nav items is related to their container size and the size of the other main nav items, not the viewport.
> 
> In order to enable products engineering teams to handle the uniqueness of their product's main nav items, it may be prudent for us to explore whether CSS media queries are going to be sufficient in all cases, or if we need to enable the use of container queries or some other mechanism for them to express the required behaviour easily.

About this, how do you think if we let the consumer handle the "responsiveness" of the main navigation
what I mean by "responsiveness" here is just whether to move the rest of the button into the menu (that said whether the whole main navigation visible or not is this ticket is our responsibility), my consideration is, although the Design Guidelines state that the TopBar is suitable for navigation with a flat hierarchy or for scenarios with eight or fewer navigation buttons (in which case, using a SideBar is recommended), there may still be users who require navigation with a non-flat hierarchy, similar to what Jira offers. If we need to transition to a navigation dropdown menu, it could be challenging since we currently do not support nested menus—at least not yet.

so in my plan how the consumer need to do is something like this:
```javascript
// TopBar is part of the new ElementNav
<ElementNav
   leftSection={{
     brandUrl, // (optional)
     mainNavigations:[
       {
         label: "flat nav button 1"
         onClick,
         // or
         href: '/page 1'
       },
       {
         label: "non flat nav button"
         items: [
           { 
             onClick,
             // or
             href: '/page 1'
           }
         ]
       },
       {
         label: "flat nav button 2"
         onClick
       },
       {
         label: "flat nav button 3"
         onClick
       },
       {
         label: "More button"
         items: [
           { 
             onClick,
             // or
             href: '/page 1'
           }
          // ... nav button 4 to 6 .ettc
         ]
       }
 '
       }
     ]
   }} ... />
```

**Comment by kurtdoherty** [comment] 2024-11-20 22:34
We need to keep our thinking focused on `TopBar`, not this proposed `ElementsNav` that we don't have agreement on yet.

> About this, how do you think if we let the consumer handle the "responsiveness" of the main navigation

Here's one possible way we could allow consumers to handle the unique requirements of their products main nav items: https://codesandbox.io/p/sandbox/78hkcg

For this ticket, I think we just want to scope the work to creating a `TopBar` component that has a good collection of props that allow it to decide when and where the different "pieces" of the top bar are displayed. Everything else can be dealt with separately.

**Comment by nurm717123** [comment] 2024-11-21 03:16
> We need to keep our discussion focused on TopBar, not this proposed ElementsNav component, as we don't have agreement on that yet.

ok, got it

> Here's one possible way we could allow consumers to handle the unique requirements of their products main nav items: https://codesandbox.io/p/sandbox/78hkcg

thanks for the detailed example 👍 , I have checked it and I think it work (except in Firefox), I will try if there is some way to handle that

by that mean, can I assume that its still ok to let consumer use e.g:
- nav item 1 (flat)
- ... ( nav item 2 to 6)
- nav item 7 (nav dropdown menu)

when 7th and 6th item need to be collapsed, it would not be supported currently.

**Comment by nurm717123** [comment] 2024-11-21 05:19
I have tried another approach and it works in Firefox

https://codesandbox.io/p/sandbox/poc-container-query-component-forked-j8wz5x?file=%2Fsrc%2FApp.js%3A52%2C43&workspaceId=18193654-17c4-4a07-8475-7fa9d3aac0b9

**Comment by kurtdoherty** [comment] 2024-11-21 06:03
Ah, that's a pain. I didn't notice Firefox doesn't fully support scoped CSS styles; Firefox works fine with the `@container` query so I've updated my POC to avoid the use of the scoped CSS. While your solution works, it's quite "heavy" and, because it's all in JS, loses out on some of the expressiveness of the CSS container query conditions.

> when 7th and 6th item need to be collapsed, it would not be supported currently, so we can ignore it for now and let consumer to use the sidebar.

That's for the design team to work out. They have the option of using the sidebar to avoid the menu-based nav item 7; they also have the option of collapsing nav item 7's menu items into a group of menu items in the "More" item. That stuff is not really our concern, unless they decide they want nested menus.

**Comment by nurm717123** [comment] 2024-11-21 13:06
> Ah, that's a pain. I didn't notice Firefox doesn't fully support scoped CSS styles; Firefox works fine with the @container query so I've updated my POC to avoid the use of the scoped CSS. 

Thanks for the updated CodeSandbox, the current typings seems to haven't support it but we can use the `<style>` tag for now, I believe it will work, so I'll try to make a pr after this 👍

**Comment by nurm717123** [comment] 2024-11-24 13:01
After testing this in my PR and reviewing the latest design spec, which suggests that the main nav buttons should not have a limit in number and should be hidden when the space becomes too narrow, I noticed a limitation with relying solely on container queries. The issue is that the main nav button lengths vary based on their labels, making it difficult to determine which buttons should be hidden. I think the easiest solution is to use a JavaScript approach because it can dynamically calculate the total width of the main navigation buttons (though, as you mentioned earlier, this could be performance-heavy) 🤔 , what do you think?

**Comment by kurtdoherty** [comment] 2024-11-24 22:17
> The issue is that the main nav button lengths vary based on their labels, making it difficult to determine which buttons should be hidden.

Yes. This is what I mean above when I say "unique requirements of their products main nav items." It's also why I'm suggesting we _may_ want to provide some additional primitives (like the ContainerQuery component in my POC) that help products deal with their unique nav items.

I'm not sure its worth investing in a JS-heavy solution (yet) that does all of this "automatically." It seems fairly cheap for product designers and/or engineers to define the specific container widths at which their product's nav items should be collapsed into a "More" item 🤷‍♂️ In future, if we learn that this is too burdensome, we can go to the effort to implementing a generalised solution.

**Closed** 2024-12-17 02:54 UTC
Labels: feature, v5
